export const botonSignupLogin = ' Signup / Login';
export const campoNombre = 'signup-name';
export const campoMail = 'signup-email'
export const nombre = 'Pepito'
export const apellido = 'Test'
export const tempMail = 'selip98320@bizmud.com'; /*correo temporal creado con https://temp-mail.org/es */
export const performanceText = 'Enter Account Information';
export const password = 'passtest'
export const diaNac= '12'
export const mesNac='4'
export const yearNac='1990'
export const direccion = 'CalleFalsa'
export const pais = 'Canada'
export const estado = 'Quebec'
export const ciudad = 'Quebec'
export const cp = 'g0a 1h0'
export const celular = '1599996539'